// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	measurement "github.com/mariuscristian/speedtest/domain/measurement"
	mock "github.com/stretchr/testify/mock"
)

// SpeedTestUseCase is an autogenerated mock type for the SpeedTestUseCase type
type SpeedTestUseCase struct {
	mock.Mock
}

// MeasureSpeed provides a mock function with given fields: method
func (_m *SpeedTestUseCase) MeasureSpeed(method measurement.SpeedTestServerType) measurement.SpeedTestResult {
	ret := _m.Called(method)

	var r0 measurement.SpeedTestResult
	if rf, ok := ret.Get(0).(func(measurement.SpeedTestServerType) measurement.SpeedTestResult); ok {
		r0 = rf(method)
	} else {
		r0 = ret.Get(0).(measurement.SpeedTestResult)
	}

	return r0
}
